// <auto-generated />
using ATMAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATMAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241125172339_Operations")]
    partial class Operations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATMAPI.Model.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperationName = "Register"
                        },
                        new
                        {
                            Id = 2,
                            OperationName = "Login"
                        },
                        new
                        {
                            Id = 3,
                            OperationName = "CheckBalance"
                        },
                        new
                        {
                            Id = 4,
                            OperationName = "Deposit"
                        },
                        new
                        {
                            Id = 5,
                            OperationName = "Withdraw"
                        },
                        new
                        {
                            Id = 6,
                            OperationName = "TransferMoney"
                        },
                        new
                        {
                            Id = 7,
                            OperationName = "RecieveMoney"
                        },
                        new
                        {
                            Id = 8,
                            OperationName = "RemoveUser"
                        },
                        new
                        {
                            Id = 9,
                            OperationName = "LogOut"
                        });
                });

            modelBuilder.Entity("ATMAPI.Model.UserCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ordinary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
